import 'package:flutter/material.dart';

class zonaMyM {
  String tituloFase;
  String title;
  String information;
  String basicInformation;
  String ejercicios;
  String imageUrl;
  int itemTipoRecuperamient;
  int itemFaseHombro;
  int itemPatologia;

  zonaMyM(
      {required this.tituloFase,
      required this.title,
      required this.information,
      required this.basicInformation,
      required this.ejercicios,
      required this.imageUrl,
      required this.itemTipoRecuperamient,
      required this.itemFaseHombro,
      required this.itemPatologia});
}

// ********** FASES DE HOMBRO **********
List<zonaMyM> faseListZona = [
  zonaMyM(
    tituloFase: "",
    title: "Fase Aguda",
    information: "Controla la incomodidad y reduce la inflamación.",
    basicInformation:
        "Reactiva tu bienestar. Controla la incomodidad, reduce la inflamación y recupera tu hombro con tratamientos efectivos.",
    ejercicios: "",
    imageUrl: 'assets/hAgudo.PNG',
    itemTipoRecuperamient: 0,
    itemPatologia: 0,
    itemFaseHombro: 0,
  ),
  zonaMyM(
      tituloFase: "",
      title: "Fase Cronica",
      information: "Mejora la movilidad y funcionalidad.",
      basicInformation:
          "Si persisten las molestias y limitaciones en el hombro, este tratamiento ayudara a mejorar la movilidad, fuerza y funcionalidad a largo plazo.",
      ejercicios: "",
      imageUrl: 'assets/hCronico.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 0,
      itemFaseHombro: 1),
  zonaMyM(
    tituloFase: "",
    title: "Mantenimiento",
    information: "Evita recaídas y asegura un hombro fuerte.",
    basicInformation:
        "Continúa avanzando en tu bienestar, evita recaídas y asegura un hombro fuerte y funcional para una vida sin limitaciones.",
    ejercicios: "",
    imageUrl: 'assets/hMantenimiento.PNG',
    itemTipoRecuperamient: 0,
    itemPatologia: 0,
    itemFaseHombro: 2,
  ),
];

// ********** FASES DE CODO **********
List<zonaMyM> faseListZonaCodo = [
  zonaMyM(
      tituloFase: "",
      title: "Fase Aguda",
      information: "Controla el malestar y reduce la inflamación.",
      basicInformation:
          "Dale un giro a tu proceso de recuperación. Controla el malestar, reduce la inflamación y repara tu codo con tratamientos efectivos.",
      ejercicios: "",
      imageUrl: 'assets/cAgudo.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 1,
      itemFaseHombro: 0),
  zonaMyM(
      tituloFase: "",
      title: "Fase Cronica",
      information: "Mejora la movilidad y funcionalidad para el futuro.",
      basicInformation:
          "Si persisten las molestias y limitaciones en el codo, nos centraremos en mejorar la movilidad, fuerza y funcionalidad para el futuro.",
      ejercicios: "",
      imageUrl: 'assets/cCronico.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 1,
      itemFaseHombro: 1),
  zonaMyM(
      tituloFase: "",
      title: "Mantenimiento",
      information: "Evita recaídas y asegura un codo fuerte",
      basicInformation:
          "Sigue avanzando con perseverancia, evita recaídas y asegura un codo fuerte y funcional para una vida plena.",
      ejercicios: "",
      imageUrl: 'assets/cMantenimiento.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 1,
      itemFaseHombro: 2),
];

// ********** FASES DE MUÑECA**********
List<zonaMyM> faseListZonaMuneca = [
  zonaMyM(
      tituloFase: "",
      title: "Fase Aguda",
      information: "Controla el dolor y reduce la inflamación.",
      basicInformation:
          "Emprende el camino hacia la recuperación: Controla el dolor, reduce la inflamación y rehabilita tu mano con tratamientos efectivos.",
      ejercicios: "",
      imageUrl: 'assets/mAgudo.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 2,
      itemFaseHombro: 0),
  zonaMyM(
      tituloFase: "",
      title: "Fase Cronica",
      information: "Mejora la movilidad y funcionalidad a largo plazo.",
      basicInformation:
          "Si las molestias y limitaciones en la mano persisten, el tratamiento se enfocará en mejorar la movilidad, fuerza y funcionalidad a largo plazo.",
      ejercicios: "",
      imageUrl: 'assets/mCronico.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 2,
      itemFaseHombro: 1),
  zonaMyM(
      tituloFase: "",
      title: "Mantenimiento",
      information: "Evita recaídas y asegura una mano fuerte.",
      basicInformation:
          "Continúa progresando, evita recaídas y asegura una mano fuerte y funcional para una vida sin restricciones.",
      ejercicios: "",
      imageUrl: 'assets/mMantenimiento.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 2,
      itemFaseHombro: 2),
];

// ********** FASES DE MANO **********
List<zonaMyM> faseListZonaMano = [
  zonaMyM(
      tituloFase: "",
      title: "Fase Aguda",
      information: "Controla el dolor y reduce la inflamación.",
      basicInformation:
          "Inicia tu ruta hacia la recuperación. Controla el dolor, reduce la inflamación y rehabilita tu muñeca con tratamientos efectivos.",
      ejercicios: "",
      imageUrl: 'assets/mnAgudo.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 3,
      itemFaseHombro: 0),
  zonaMyM(
      tituloFase: "",
      title: "Fase Cronica",
      information: "Mejora la movilidad y funcionalidad.",
      basicInformation:
          "Si las molestias y limitaciones en la muñeca persisten, nos enfocaremos en mejorar la movilidad, fuerza y funcionalidad para el futuro.",
      ejercicios: "",
      imageUrl: 'assets/mnCronico.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 3,
      itemFaseHombro: 1),
  zonaMyM(
      tituloFase: "",
      title: "Mantenimiento",
      information: "Evita recaídas y asegura una muñeca fuerte.",
      basicInformation:
          "Continúa avanzando, evita recaídas y asegura una muñeca fuerte y funcional para una vida sin limitaciones.",
      ejercicios: "",
      imageUrl: 'assets/mnMantenimiento.PNG',
      itemTipoRecuperamient: 0,
      itemPatologia: 3,
      itemFaseHombro: 2),
];

// Hombro

//Fase Aguda Hombro
List<zonaMyM> tipoRecuperamientoAgudoHombro = [
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hMovilidad1.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFortalecimiento1.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFlexibilidad1.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hDolor1.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
];
//Fase Cronica Hombro
List<zonaMyM> tipoRecuperamientoCronicoHombro = [
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hMovilidad1.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFortalecimiento1.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFlexibilidad1.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hDolor1.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
];
//Fase Mantenimiento Hombro
List<zonaMyM> zonaMyMListZonaTresHombro = [
  zonaMyM(
    tituloFase: "Fase de Mantenimiento",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hombro11.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 3,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase de Mantenimiento",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/codo11.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 3,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase de Mantenimiento",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/mano11.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 3,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase de Mantenimiento",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/mano11.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 3,
    itemPatologia: 0,
  ),
];

// Avd de Fase aguda y cronica Hombro
List<zonaMyM> botonesListAvdAgudaHombro = [
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 0,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 0,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 0,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Alimentacion",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 0,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 0,
    itemPatologia: 0,
  ),
  //Fase aguda otra pantalla
];
List<zonaMyM> botonesListAvdCronicaHombro = [
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Alimentación",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 1,
    itemPatologia: 0,
  ),
  //Fase aguda otra pantalla
];

// Avd de Reentrenaimiento Hombro
List<zonaMyM> botonesListAvdMantenimientoHombro = [
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Alimentación",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 2,
    itemPatologia: 0,
  ),
];

// Codo

//Fase Aguda Hombro
List<zonaMyM> tipoRecuperamientoAgudoCodo = [
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hMovilidad1.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFortalecimiento1.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFlexibilidad1.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hDolor1.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
];
//Fase Cronica Hombro
List<zonaMyM> tipoRecuperamientoCronicoCodo = [
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hMovilidad1.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFortalecimiento1.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFlexibilidad1.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hDolor1.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
];

// Avd de Fase aguda y cronica Codo
List<zonaMyM> botonesListAvdAgudaCodo = [
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 0,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 0,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 0,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Alimentacion",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 0,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 0,
    itemPatologia: 1,
  ),
];
List<zonaMyM> botonesListAvdCronicaCodo = [
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Alimentación",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
];

// Avd de Reentrenaimiento Codo
List<zonaMyM> botonesListAvdMantenimientoCodo = [
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Alimentación",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
];

// Muñeca

//Fase Aguda Muñeca
List<zonaMyM> tipoRecuperamientoAgudoMuneca = [
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hMovilidad1.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFortalecimiento1.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFlexibilidad1.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hDolor1.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
];
//Fase Cronica Muñeca
List<zonaMyM> tipoRecuperamientoCronicoMuneca = [
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hMovilidad1.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFortalecimiento1.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFlexibilidad1.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hDolor1.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
];

// Avd de Fase aguda y cronica Muñeca
List<zonaMyM> botonesListAvdAgudaMuneca = [
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 0,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 0,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 0,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Alimentacion",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 0,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 0,
    itemPatologia: 2,
  ),
];
List<zonaMyM> botonesListAvdCronicaMuneca = [
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 1,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 1,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 1,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Alimentación",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 1,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 1,
    itemPatologia: 2,
  ),
];

// Avd de Reentrenaimiento Muñeca
List<zonaMyM> botonesListAvdMantenimientoMuneca = [
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 2,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 2,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 2,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Alimentación",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 2,
    itemPatologia: 2,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 2,
    itemPatologia: 2,
  ),
];

// Mano

//Fase Aguda Mano
List<zonaMyM> tipoRecuperamientoAgudoMano = [
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hMovilidad1.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFortalecimiento1.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFlexibilidad1.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hDolor1.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 1,
    itemPatologia: 1,
  ),
];
//Fase Cronica Mano
List<zonaMyM> tipoRecuperamientoCronicoMano = [
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Movilidad Articular",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hMovilidad1.png',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Fortalecimiento",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFortalecimiento1.png',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Flexibilidad",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hFlexibilidad1.png',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Manejo del Dolor",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/hDolor1.png',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 2,
    itemPatologia: 1,
  ),
];

// Avd de Fase aguda y cronica Mano
List<zonaMyM> botonesListAvdAgudaMano = [
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 0,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 0,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 0,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Alimentacion",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 0,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Aguda",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 0,
    itemPatologia: 3,
  ),
];
List<zonaMyM> botonesListAvdCronicaMano = [
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 1,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 1,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 1,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Alimentación",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 1,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Cronica",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 1,
    itemPatologia: 3,
  ),
];

// Avd de Reentrenaimiento Mano
List<zonaMyM> botonesListAvdMantenimientoMano = [
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Bañarse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdBañarse.jpg',
    itemTipoRecuperamient: 0,
    itemFaseHombro: 2,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Vestirse",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdVestirse.jpg',
    itemTipoRecuperamient: 1,
    itemFaseHombro: 2,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Comer",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdComer.jpg',
    itemTipoRecuperamient: 2,
    itemFaseHombro: 2,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Alimentación",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdAlimentacion.jpg',
    itemTipoRecuperamient: 3,
    itemFaseHombro: 2,
    itemPatologia: 3,
  ),
  zonaMyM(
    tituloFase: "Fase Mantenimiento",
    title: "Higiene y Arreglo",
    information: " ",
    basicInformation: "",
    ejercicios: "",
    imageUrl: 'assets/avdHigiene.jpg',
    itemTipoRecuperamient: 4,
    itemFaseHombro: 2,
    itemPatologia: 3,
  ),
];
